import{useState}from"react";
import{Tgl,IB}from"./widgets.jsx";
import{protOrder,curveTypes,TEST_PRESETS,biRows,cbStatusRows,cbCmdRows,protStageRows,allRows,boCols,ledCols,allCols,inMatrixRows}from"./defaults.js";
import{useTranslation}from"./i18n/useTranslation.js";
import{calc21FaultDistance}from"./protection.js";
import ScenariosSidebar from"./relay/ScenariosSidebar.jsx";

// ── Main SettingsPanel export ─────────────────────────────────────────────────
export default function SettingsPanel({prot,outMatrix,inMatrix,sys,tab,si,mainTab,uPr,uSt,uS,setSi,setTab,toggleMatrix,toggleInMatrix,applyTestPreset,rtp,rtc,phasors,settingGroups,activeGroup,switchGroup,copyGroup}){
  const{t}=useTranslation();
  const[presetsOpen,setPresetsOpen]=useState(false);
  const[copyOpen,setCopyOpen]=useState(false);
  const[copyFrom,setCopyFrom]=useState(0);const[copyTo,setCopyTo]=useState(1);
  const groupCount=Array.isArray(settingGroups)?settingGroups.length:4;
  const getStages=()=>{const f=prot[tab];if(tab==="27/59")return[...(f.stages27||[]),...(f.stages59||[])];if(tab==="81")return[...(f.stages81u||[]),...(f.stages81o||[])];if(tab==="32")return[...(f.stages32r||[]),...(f.stages32f||[])];if(tab==="87")return f.stages87||[];if(tab==="21")return f.stages21||[];if(tab==="50BF")return f.stages50bf||[];if(tab==="49")return f.stages49||[];if(tab==="25")return f.stages25||[];if(tab==="81R")return f.stages81r||[];if(tab==="79")return[];return f.stages||[]};
  const getCur=()=>{if(tab==="27/59"){return si<3?prot["27/59"].stages27?.[si]:prot["27/59"].stages59?.[si-3]}if(tab==="81"){return si<3?prot["81"].stages81u?.[si]:prot["81"].stages81o?.[si-3]}if(tab==="32"){return si<2?prot["32"].stages32r?.[si]:prot["32"].stages32f?.[si-2]}if(tab==="87")return(prot["87"].stages87||[])[si];if(tab==="21")return(prot["21"].stages21||[])[si];if(tab==="50BF")return(prot["50BF"].stages50bf||[])[si];if(tab==="49")return(prot["49"].stages49||[])[si];if(tab==="25")return(prot["25"].stages25||[])[si];if(tab==="81R")return(prot["81R"].stages81r||[])[si];if(tab==="79")return null;return(prot[tab].stages||[])[si]};
  const isOC=["50","51","50N","51N","67","67N"].includes(tab);const isTm=["51","51N","67","67N"].includes(tab);const isDir=["67","67N"].includes(tab);const isVlt=tab==="27/59";const is46=tab==="46";const is81=tab==="81";const is32=tab==="32";const is79=tab==="79";const is87=tab==="87";const is21=tab==="21";const is50bf=tab==="50BF";const is49=tab==="49";const is25=tab==="25";const is81r=tab==="81R";const is60=tab==="60";
  const stages=getStages();const cur=getCur();
  const inj87=prot["87"]?.inj87||{IW1:{mag:0,ang:0},IW2:{mag:0,ang:0},h2pct:0};
  const u87w=(w,fld,v)=>uPr("87","inj87",{...inj87,[w]:{...inj87[w],[fld]:v}});
  const u87h=v=>uPr("87","inj87",{...inj87,h2pct:v});
  const ref25=prot["25"]?.ref25||{Vmag:66.4,Vang:0,fHz:60};
  const u25ref=(fld,v)=>uPr("25","ref25",{...ref25,[fld]:v});
  const inj81r=prot["81R"]?.inj81r||{dfdt:0};
  const u81rdf=v=>uPr("81R","inj81r",{...inj81r,dfdt:v});

  if(mainTab==="sys")return(<div className="card-scroll"><div className="cp"><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:14}}><div><div className="fn" style={{marginBottom:10}}>{t("sys.pt")}</div><div className="fr"><div className="fg"><div className="fl">{t("sys.vPri")}</div><IB unit="V" value={sys.tp.priV} onChange={v=>uS("tp","priV",v)}/></div><div className="fg"><div className="fl">{t("sys.vSec")}</div><IB unit="V" value={sys.tp.secV} onChange={v=>uS("tp","secV",v)}/></div></div><div className="fl" style={{margin:"6px 0 3px"}}>{t("sys.primary")}</div><div className="conn-r"><button className={`conn-b ${sys.tp.priConn==="estrela"?"on":""}`} onClick={()=>uS("tp","priConn","estrela")}>Y</button><button className={`conn-b ${sys.tp.priConn==="delta"?"on":""}`} onClick={()=>uS("tp","priConn","delta")}>Δ</button></div><div className="fl" style={{margin:"6px 0 3px"}}>{t("sys.secondary")}</div><div className="conn-r"><button className={`conn-b ${sys.tp.secConn==="estrela"?"on":""}`} onClick={()=>uS("tp","secConn","estrela")}>Y</button><button className={`conn-b ${sys.tp.secConn==="delta"?"on":""}`} onClick={()=>uS("tp","secConn","delta")}>Δ</button></div><div className="ratio">{t("sys.rtp")}{rtp.toFixed(2)}</div></div><div><div className="fn" style={{marginBottom:10}}>{t("sys.ct")}</div><div className="fr"><div className="fg"><div className="fl">{t("sys.iPri")}</div><IB unit="A" value={sys.tc.priA} onChange={v=>uS("tc","priA",v)}/></div><div className="fg"><div className="fl">{t("sys.iSec")}</div><IB unit="A" value={sys.tc.secA} onChange={v=>uS("tc","secA",v)}/></div></div><div className="ratio">{t("sys.rtc")}{rtc.toFixed(2)}</div></div></div></div></div>);

  if(mainTab==="relay")return(<><div className="tp-dropdown" style={{position:"relative",padding:"8px 14px",borderBottom:"1px solid var(--bdr)",flexShrink:0}}><button className="tp-btn-dropdown" onClick={()=>setPresetsOpen(!presetsOpen)} style={{padding:"8px 14px",background:"var(--card2)",border:"1px solid var(--bdr)",borderRadius:"var(--rs)",color:"var(--tx2)",fontSize:11,fontWeight:700,cursor:"pointer",width:"100%",textAlign:"left"}}>{t("settings.preset")} ▼</button>{presetsOpen&&<div style={{position:"absolute",top:"100%",left:0,right:0,background:"var(--card)",border:"1px solid var(--bdr)",borderRadius:"var(--rs)",marginTop:4,zIndex:100,maxHeight:"200px",overflowY:"auto",boxShadow:"0 4px 12px rgba(0,0,0,.3)"}}>{TEST_PRESETS.map(p=><button key={p.id} style={{display:"block",width:"100%",padding:"10px 14px",border:"none",background:"transparent",color:"var(--tx2)",fontSize:11,fontWeight:600,textAlign:"left",cursor:"pointer",borderBottom:"1px solid var(--bdr)",transition:"all .2s"}} onMouseEnter={e=>e.target.style.background="var(--card2)"} onMouseLeave={e=>e.target.style.background="transparent"} title={p.desc} onClick={()=>{applyTestPreset(p);setPresetsOpen(false)}}>{p.label}</button>)}</div>}</div>
    {typeof switchGroup==="function"&&<div className="sg-bar" style={{display:"flex",alignItems:"center",gap:6,padding:"6px 14px",borderBottom:"1px solid var(--bdr)",flexShrink:0,position:"relative"}}>
      <span style={{fontSize:9,fontWeight:700,color:"var(--tx3)",letterSpacing:".8px",textTransform:"uppercase"}}>Grupo</span>
      {Array.from({length:groupCount}).map((_,i)=><button key={i} className="sg-pill" onClick={()=>switchGroup(i)} title={`Grupo de ajustes G${i+1}${i===activeGroup?" (ativo)":""}`} style={{padding:"5px 10px",borderRadius:6,fontSize:10,fontWeight:700,fontFamily:"var(--fm)",cursor:"pointer",border:`1.5px solid ${i===activeGroup?"var(--orange)":"var(--bdr)"}`,background:i===activeGroup?"var(--orange-dim)":"var(--card3)",color:i===activeGroup?"var(--orange)":"var(--tx3)",transition:"all .2s"}}>{`G${i+1}`}</button>)}
      {typeof copyGroup==="function"&&<button className="sg-copy" onClick={()=>setCopyOpen(o=>!o)} title="Copiar ajustes entre grupos" style={{marginLeft:"auto",padding:"5px 10px",borderRadius:6,fontSize:10,fontWeight:700,cursor:"pointer",border:"1px solid var(--bdr)",background:"var(--card2)",color:"var(--tx2)"}}>Copiar…</button>}
      {copyOpen&&typeof copyGroup==="function"&&<div style={{position:"absolute",top:"100%",right:14,background:"var(--card)",border:"1px solid var(--bdr)",borderRadius:"var(--rs)",marginTop:4,zIndex:100,padding:8,display:"flex",alignItems:"center",gap:6,boxShadow:"0 4px 12px rgba(0,0,0,.3)"}}>
        <select className="sl" value={copyFrom} onChange={e=>setCopyFrom(Number(e.target.value))} style={{fontSize:10,padding:"3px 6px"}}>{Array.from({length:groupCount}).map((_,i)=><option key={i} value={i}>{`G${i+1}`}</option>)}</select>
        <span style={{fontSize:11,color:"var(--tx3)"}}>→</span>
        <select className="sl" value={copyTo} onChange={e=>setCopyTo(Number(e.target.value))} style={{fontSize:10,padding:"3px 6px"}}>{Array.from({length:groupCount}).map((_,i)=><option key={i} value={i}>{`G${i+1}`}</option>)}</select>
        <button onClick={()=>{copyGroup(copyFrom,copyTo);setCopyOpen(false);}} disabled={copyFrom===copyTo} style={{padding:"4px 10px",borderRadius:6,fontSize:10,fontWeight:700,cursor:copyFrom===copyTo?"not-allowed":"pointer",border:"1px solid rgba(249,115,22,.4)",background:"var(--orange-dim)",color:"var(--orange)",opacity:copyFrom===copyTo?.5:1}}>OK</button>
      </div>}
    </div>}
    <div className="card-scroll"><div className="cp">
    <div className="fh"><span className="fn">{prot[tab].name}</span><Tgl value={prot[tab].enabled} onChange={v=>uPr(tab,"enabled",v)} label={prot[tab].enabled?t("settings.enabled"):t("settings.disabled")}/></div>
    {isOC&&<div className="bs"><label>{t("settings.adjustBase")}</label><select className="sl" value={prot[tab].base} onChange={e=>uPr(tab,"base",e.target.value)}><option value="primario">{t("settings.primary")}</option><option value="secundario">{t("settings.secondary")}</option><option value="multiplo">{t("settings.multiple")}</option></select></div>}
    {isVlt&&<div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:8,marginBottom:10}}>
      <div className="bs"><label>{t("settings.startPhases")}</label><select className="sl" value={prot[tab].startPhases||"any"} onChange={e=>uPr(tab,"startPhases",e.target.value)}><option value="any">{t("settings.anyPhase")}</option><option value="all">{t("settings.allPhases")}</option></select></div>
      <div className="bs"><label>{t("settings.voltageSelection")}</label><select className="sl" value={prot[tab].voltageSelection||"ph-n"} onChange={e=>uPr(tab,"voltageSelection",e.target.value)}><option value="ph-n">{t("settings.phaseNeutral")}</option><option value="ph-ph">{t("settings.phasePhase")}</option></select></div>
      <div className="bs"><label>{t("settings.hysteresis")}</label><IB unit="%" value={prot[tab].hysteresis||4.0} onChange={v=>uPr(tab,"hysteresis",v)} step="0.1"/></div>
      <div className="bs"><Tgl value={prot[tab].lowVoltageBlockEnabled||false} onChange={v=>uPr(tab,"lowVoltageBlockEnabled",v)} label={t("settings.lowVBlock")}/>{prot[tab].lowVoltageBlockEnabled&&<div style={{marginTop:4}}><IB unit="pu" value={prot[tab].voltageBlockPu||0.20} onChange={v=>uPr(tab,"voltageBlockPu",v)} step="0.01"/></div>}</div>
    </div>}
    <div style={{padding:"8px",background:"var(--card2)",borderRadius:"var(--rs)",marginBottom:10}}><div style={{fontSize:9,fontWeight:700,color:"var(--tx3)",letterSpacing:".8px",textTransform:"uppercase",marginBottom:6}}>{t("settings.stages")}</div><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit, minmax(60px, 1fr))",gap:4}}>{stages.map((s,i)=><button key={s.id} className={`stage-btn${i===si?" on":""} ${!s.enabled?"disabled":""}`} onClick={()=>setSi(i)} style={{padding:"8px 6px",borderRadius:"6px",border:`1.5px solid ${i===si?"var(--orange)":"var(--bdr)"}`,background:i===si?"var(--orange-dim)":"var(--card3)",color:i===si?"var(--orange)":!s.enabled?"var(--tx4)":"var(--tx2)",fontSize:11,fontWeight:700,cursor:"pointer",transition:"all .2s",opacity:!s.enabled?0.5:1}}>{s.id}</button>)}</div></div>
    {is46&&<div className="bs" style={{marginBottom:8,padding:"6px 8px",background:"var(--card2)",borderRadius:"var(--rs)",fontSize:10,color:"var(--tx3)"}}>{t("customScenarios.info46")}</div>}
    {is81&&<div className="bs" style={{marginBottom:8,padding:"6px 8px",background:"var(--card2)",borderRadius:"var(--rs)",fontSize:10,color:"var(--tx3)"}}>{t("customScenarios.info81")}</div>}
    {is32&&<div className="bs" style={{marginBottom:8,padding:"6px 8px",background:"var(--card2)",borderRadius:"var(--rs)",fontSize:10,color:"var(--tx3)"}}>{t("customScenarios.info32")}</div>}
    {is21&&<><div className="bs" style={{marginBottom:8,padding:"6px 8px",background:"var(--card2)",borderRadius:"var(--rs)",fontSize:10,color:"var(--tx3)"}}>A 21 mede Z=V/I no loop de fase com maior corrente, usando a injeção global de Tensão e Corrente. Cada zona dispara (tempo definido) quando Z entra na característica. Valores em Ω secundário.</div>
      <div style={{padding:"8px",background:"var(--card2)",borderRadius:"var(--rs)",marginBottom:10}}><div style={{fontSize:9,fontWeight:700,color:"var(--tx3)",letterSpacing:".8px",textTransform:"uppercase",marginBottom:6}}>Localizador de Falta</div><div className="pg">
        <div className="pi"><label>Comprimento (km)</label><IB unit="km" value={prot["21"]?.lineLen??10} onChange={v=>uPr("21","lineLen",v)} step="1"/></div>
        <div className="pi"><label>X total (Ω sec)</label><IB unit="Ω" value={prot["21"]?.xLineTotal??10} onChange={v=>uPr("21","xLineTotal",v)} step="0.5"/></div>
      </div>
      {(()=>{
        const rrLive={
          currents:{Ia:{mag:(phasors?.currents?.Ia?.mag??0)*rtc,ang:phasors?.currents?.Ia?.ang??0},Ib:{mag:(phasors?.currents?.Ib?.mag??0)*rtc,ang:phasors?.currents?.Ib?.ang??-120},Ic:{mag:(phasors?.currents?.Ic?.mag??0)*rtc,ang:phasors?.currents?.Ic?.ang??120}},
          voltages:{Va:{mag:(phasors?.voltages?.Va?.mag??0)*rtp,ang:phasors?.voltages?.Va?.ang??0},Vb:{mag:(phasors?.voltages?.Vb?.mag??0)*rtp,ang:phasors?.voltages?.Vb?.ang??-120},Vc:{mag:(phasors?.voltages?.Vc?.mag??0)*rtp,ang:phasors?.voltages?.Vc?.ang??120}},
        };
        const d=calc21FaultDistance(rrLive,prot["21"]);
        if(d===null)return null;
        return <div style={{marginTop:6,padding:"4px 8px",background:"var(--card3,var(--card))",borderRadius:"var(--rs)",fontFamily:"var(--fm)",fontSize:12,color:"var(--mint)",fontWeight:700}}>Falta a {d.toFixed(1)} km</div>;
      })()}
      </div>
    </>}
    {is79&&<div style={{marginTop:4}}><div style={{marginBottom:8,padding:"6px 8px",background:"var(--card2)",borderRadius:"var(--rs)",fontSize:10,color:"var(--tx3)"}}>{t("customScenarios.info79dead")}</div><div className="pg"><div className="pi"><label>{t("settings.shots")}</label><IB unit="shots" value={prot["79"].shots??3} onChange={v=>uPr("79","shots",Math.max(1,Math.round(v)))}/></div><div className="pi"><label>{t("settings.reclaimTime")}</label><IB unit="s" value={prot["79"].reclaimTime??3.0} onChange={v=>uPr("79","reclaimTime",v)} step="0.1"/></div></div><div style={{marginTop:8}}><div className="fl" style={{marginBottom:4}}>{t("settings.deadTimes")}</div>{(prot["79"].deadTimes||[0.5,5.0,15.0]).map((dt,i)=><div key={i} className="fr" style={{marginBottom:4}}><div className="fg"><div className="fl">{t("settings.shot")} {i+1}</div><IB unit="s" value={dt} onChange={v=>{const dts=[...(prot["79"].deadTimes||[0.5,5.0,15.0])];dts[i]=v;uPr("79","deadTimes",dts);}} step="0.1"/></div></div>)}</div></div>}
    {is87&&<div style={{padding:"8px",background:"var(--card2)",borderRadius:"var(--rs)",marginBottom:10}}><div style={{fontSize:9,fontWeight:700,color:"var(--tx3)",letterSpacing:".8px",textTransform:"uppercase",marginBottom:6}}>Injeção 87 — dois enrolamentos (A sec)</div><div className="pg">
      <div className="pi"><label>IW1 — mag</label><IB unit="A" value={inj87.IW1.mag} onChange={v=>u87w("IW1","mag",v)} step="0.1"/></div>
      <div className="pi"><label>IW1 — âng</label><IB unit="°" value={inj87.IW1.ang} onChange={v=>u87w("IW1","ang",v)} step="1"/></div>
      <div className="pi"><label>IW2 — mag</label><IB unit="A" value={inj87.IW2.mag} onChange={v=>u87w("IW2","mag",v)} step="0.1"/></div>
      <div className="pi"><label>IW2 — âng</label><IB unit="°" value={inj87.IW2.ang} onChange={v=>u87w("IW2","ang",v)} step="1"/></div>
      <div className="pi"><label>2ª harmônica</label><IB unit="%" value={inj87.h2pct} onChange={v=>u87h(v)} step="1"/></div>
    </div></div>}
    {is50bf&&<div className="bs" style={{marginBottom:8,padding:"6px 8px",background:"var(--card2)",borderRadius:"var(--rs)",fontSize:10,color:"var(--tx3)"}}>A 50BF verifica que a corrente de fase persiste acima do pickup e, após o tempo tBF, comanda o re-trip / trip de retaguarda. Usa a injeção global de Corrente. Valores em A secundário.</div>}
    {is49&&<div className="bs" style={{marginBottom:8,padding:"6px 8px",background:"var(--card2)",borderRadius:"var(--rs)",fontSize:10,color:"var(--tx3)"}}>A 49 (imagem térmica) atua quando I &gt; Iθ = k·Ib pelo modelo t = τ·ln[(I²−Ip²)/(I²−Iθ²)]. τ em segundos (escala didática). Usa a injeção global de Corrente.</div>}
    {is25&&<><div className="bs" style={{marginBottom:8,padding:"6px 8px",background:"var(--card2)",borderRadius:"var(--rs)",fontSize:10,color:"var(--tx3)"}}>A 25 compara o lado vivo (Va medido + frequência do sistema) com a barra de referência abaixo. Libera (SYNC OK) quando ΔV, Δθ e Δf ficam dentro dos limites por tCheck.</div>
      <div style={{padding:"8px",background:"var(--card2)",borderRadius:"var(--rs)",marginBottom:10}}><div style={{fontSize:9,fontWeight:700,color:"var(--tx3)",letterSpacing:".8px",textTransform:"uppercase",marginBottom:6}}>Barra de referência (sincronismo)</div><div className="pg">
        <div className="pi"><label>V referência</label><IB unit="V" value={ref25.Vmag} onChange={v=>u25ref("Vmag",v)} step="0.1"/></div>
        <div className="pi"><label>Âng. referência</label><IB unit="°" value={ref25.Vang} onChange={v=>u25ref("Vang",v)} step="1"/></div>
        <div className="pi"><label>Freq. referência</label><IB unit="Hz" value={ref25.fHz} onChange={v=>u25ref("fHz",v)} step="0.01"/></div>
      </div></div></>}
    {is81r&&<><div className="bs" style={{marginBottom:8,padding:"6px 8px",background:"var(--card2)",borderRadius:"var(--rs)",fontSize:10,color:"var(--tx3)"}}>A 81R (df/dt, ROCOF) usa o valor de df/dt injetado abaixo (um snapshot não contém a derivada). Atua quando |df/dt| ≥ pickup conforme a direção. Tempo definido (tOp).</div>
      <div style={{padding:"8px",background:"var(--card2)",borderRadius:"var(--rs)",marginBottom:10}}><div style={{fontSize:9,fontWeight:700,color:"var(--tx3)",letterSpacing:".8px",textTransform:"uppercase",marginBottom:6}}>Injeção 81R — taxa de variação</div><div className="pg">
        <div className="pi"><label>df/dt</label><IB unit="Hz/s" value={inj81r.dfdt} onChange={v=>u81rdf(v)} step="0.1"/></div>
      </div></div></>}
    {is60&&<><div className="bs" style={{marginBottom:8,padding:"6px 8px",background:"var(--card2)",borderRadius:"var(--rs)",fontSize:10,color:"var(--tx3)"}}>A 60/LOP (Supervisão de TP) detecta falha de fusível de TP e bloqueia funções que dependem de tensão (21, 67, 67N, 32). Modo 1: colapso 3φ de tensão com corrente de carga. Modo 2: desequilíbrio V2/V1 sem desequilíbrio I2/I1.</div>
      <div style={{padding:"8px",background:"var(--card2)",borderRadius:"var(--rs)",marginBottom:10}}><div style={{fontSize:9,fontWeight:700,color:"var(--tx3)",letterSpacing:".8px",textTransform:"uppercase",marginBottom:6}}>Parâmetros 60/LOP</div><div className="pg">
        <div className="pi"><label>Vmin (colapso 3φ)</label><IB unit="V" value={prot["60"]?.vMin??10} onChange={v=>uPr("60","vMin",v)} step="1"/></div>
        <div className="pi"><label>V2/V1 limiar</label><IB value={prot["60"]?.v2v1Thr??0.4} onChange={v=>uPr("60","v2v1Thr",v)} step="0.05"/></div>
        <div className="pi"><label>I2/I1 limiar</label><IB value={prot["60"]?.i2i1Thr??0.3} onChange={v=>uPr("60","i2i1Thr",v)} step="0.05"/></div>
        <div className="pi"><label>Icarga mín.</label><IB unit="A" value={prot["60"]?.iLoadMin??0.2} onChange={v=>uPr("60","iLoadMin",v)} step="0.05"/></div>
      </div></div>
      <div style={{padding:"6px 8px",background:"var(--card2)",borderRadius:"var(--rs)",marginBottom:8,fontSize:10,color:"var(--tx3)"}}>Funções bloqueadas: {(prot["60"]?.blockList||["21","67","67N","32"]).join(", ")}</div>
    </>}
    {cur&&!is60&&<div><Tgl value={cur.enabled} onChange={v=>uSt(tab,si,"enabled",v)} label={`${t("settings.stage")} ${cur.id}`}/><div className="pg">
      {is87&&<><div className="pi"><label>Pickup mín. (Ipu)</label><IB unit="A" value={cur.Ipu} onChange={v=>uSt(tab,si,"Ipu",v)} step="0.05"/></div><div className="pi"><label>Joelho (knee)</label><IB unit="A" value={cur.knee} onChange={v=>uSt(tab,si,"knee",v)} step="0.5"/></div><div className="pi"><label>Slope 1</label><IB unit="%" value={cur.slope1} onChange={v=>uSt(tab,si,"slope1",v)} step="1"/></div><div className="pi"><label>Slope 2</label><IB unit="%" value={cur.slope2} onChange={v=>uSt(tab,si,"slope2",v)} step="1"/></div><div className="pi"><label>Bloqueio 2ªH</label><IB unit="%" value={cur.thr2h} onChange={v=>uSt(tab,si,"thr2h",v)} step="1"/></div><div className="pi"><label>{t("settings.timeOp")}</label><IB unit="s" value={cur.tOp} onChange={v=>uSt(tab,si,"tOp",v)} step="0.005"/></div></>}
      {is21&&<><div className="pi"><label>Característica</label><select className="sl" value={cur.type} onChange={e=>uSt(tab,si,"type",e.target.value)}><option value="mho">Mho</option><option value="quad">Quadrilátero</option></select></div><div className="pi"><label>Alcance (reach)</label><IB unit="Ω" value={cur.reach} onChange={v=>uSt(tab,si,"reach",v)} step="0.5"/></div><div className="pi"><label>Ângulo (MTA)</label><IB unit="°" value={cur.mta} onChange={v=>uSt(tab,si,"mta",v)} step="1"/></div><div className="pi"><label>Tempo da zona</label><IB unit="s" value={cur.tDelay} onChange={v=>uSt(tab,si,"tDelay",v)} step="0.05"/></div><div className="pi"><label>Bloq. subtensão</label><IB unit="V" value={cur.minV} onChange={v=>uSt(tab,si,"minV",v)} step="1"/></div></>}
      {is50bf&&<><div className="pi"><label>Pickup corrente</label><IB unit="A" value={cur.pickup} onChange={v=>uSt(tab,si,"pickup",v)} step="0.1"/></div><div className="pi"><label>Tempo BF (tBF)</label><IB unit="s" value={cur.tBF} onChange={v=>uSt(tab,si,"tBF",v)} step="0.01"/></div></>}
      {is49&&<><div className="pi"><label>Corr. base (Ib)</label><IB unit="A" value={cur.Ib} onChange={v=>uSt(tab,si,"Ib",v)} step="0.1"/></div><div className="pi"><label>Fator sobrecarga (k)</label><IB value={cur.k} onChange={v=>uSt(tab,si,"k",v)} step="0.01"/></div><div className="pi"><label>Const. térmica (τ)</label><IB unit="s" value={cur.tau} onChange={v=>uSt(tab,si,"tau",v)} step="1"/></div><div className="pi"><label>Carga prévia (Ip)</label><IB unit="×Ib" value={cur.ipPrior} onChange={v=>uSt(tab,si,"ipPrior",v)} step="0.05"/></div></>}
      {is25&&<><div className="pi"><label>ΔV máx</label><IB unit="V" value={cur.dVmax} onChange={v=>uSt(tab,si,"dVmax",v)} step="0.5"/></div><div className="pi"><label>Δθ máx</label><IB unit="°" value={cur.dAngMax} onChange={v=>uSt(tab,si,"dAngMax",v)} step="1"/></div><div className="pi"><label>Δf máx</label><IB unit="Hz" value={cur.dFmax} onChange={v=>uSt(tab,si,"dFmax",v)} step="0.01"/></div><div className="pi"><label>Tempo (tCheck)</label><IB unit="s" value={cur.tCheck} onChange={v=>uSt(tab,si,"tCheck",v)} step="0.05"/></div></>}
      {is81r&&<><div className="pi"><label>Pickup df/dt</label><IB unit="Hz/s" value={cur.pickup} onChange={v=>uSt(tab,si,"pickup",v)} step="0.1"/></div><div className="pi"><label>Direção</label><select className="sl" value={cur.dir} onChange={e=>uSt(tab,si,"dir",e.target.value)}><option value="both">Ambas</option><option value="fall">Queda</option><option value="rise">Subida</option></select></div><div className="pi"><label>{t("settings.timeOp")}</label><IB unit="s" value={cur.tOp} onChange={v=>uSt(tab,si,"tOp",v)} step="0.01"/></div></>}
      {(isOC||isDir)&&<div className="pi"><label>{tab.includes("50")?t("settings.pickupInst"):t("settings.pickupTime")}</label><IB unit="A" value={cur.pickup} onChange={v=>uSt(tab,si,"pickup",v)}/></div>}
      {(isVlt||tab==="47")&&<div className="pi"><label>{t("settings.pickupPu")}</label><IB unit="pu" value={cur.pickup} onChange={v=>uSt(tab,si,"pickup",v)} step="0.01"/></div>}
      {is46&&<div className="pi"><label>{t("settings.pickupI2")}</label><IB unit="A" value={cur.pickup} onChange={v=>uSt(tab,si,"pickup",v)} step="0.01"/></div>}
      {is81&&<div className="pi"><label>{cur.id.startsWith("81U")?t("settings.pickupSubfreq"):t("settings.pickupOverfreq")}</label><IB unit="Hz" value={cur.pickup} onChange={v=>uSt(tab,si,"pickup",v)} step="0.05"/></div>}
      {is32&&<div className="pi"><label>{cur.id.startsWith("32R")?t("settings.pickup32R"):t("settings.pickup32F")}</label><IB unit="W" value={cur.pickup} onChange={v=>uSt(tab,si,"pickup",v)} step="1"/></div>}
      {isTm&&<><div className="pi"><label>{t("settings.timeDial")}</label><IB value={cur.timeDial} onChange={v=>uSt(tab,si,"timeDial",v)} step="0.01"/></div><div className="pi"><label>{t("settings.curve")}</label><select className="sl" value={cur.curve} onChange={e=>uSt(tab,si,"curve",e.target.value)}>{curveTypes.map(c=><option key={c} value={c}>{c}</option>)}</select></div></>}
      {(!isTm&&!isVlt&&tab!=="47"&&!is46&&!is81&&!is32&&!is87&&!is21&&!is50bf&&!is49&&!is25&&!is81r&&!is60)&&<div className="pi"><label>{t("settings.timeOp")}</label><IB unit="s" value={cur.timeOp} onChange={v=>uSt(tab,si,"timeOp",v)} step="0.01"/></div>}
      {(isVlt||tab==="47"||is46||is81||is32)&&<div className="pi"><label>{t("settings.timeOp")}</label><IB unit="s" value={cur.timeOp} onChange={v=>uSt(tab,si,"timeOp",v)} step="0.01"/></div>}
      {isDir&&<><div className="pi"><label>{t("settings.mta")}</label><IB unit="°" value={cur.mta} onChange={v=>uSt(tab,si,"mta",v)} step="1"/></div><div className="pi"><label>{t("settings.polarization")}</label><select className="sl" value={cur.pol} onChange={e=>uSt(tab,si,"pol",e.target.value)}>{tab==="67"?<><option value="quadratura">Quadrature</option><option value="quad_loop">Quad. Loop</option><option value="seq_pos">Positive Seq.</option><option value="seq_pos_loop">Pos. Seq. Loop</option></>:<><option value="-V0">−V₀</option><option value="V0">V₀</option></>}</select></div><div className="pi"><label>{t("settings.direction")}</label><select className="sl" value={cur.dir||"forward"} onChange={e=>uSt(tab,si,"dir",e.target.value)}><option value="forward">{t("settings.forward")}</option><option value="reverse">{t("settings.reverse")}</option></select></div>{tab==="67N"&&<div className="pi"><label>{t("settings.vminPol")}</label><IB unit="V" value={cur.minPolV} onChange={v=>uSt(tab,si,"minPolV",v)} step="0.1"/></div>}</>}
    </div></div>}
  </div></div></>);

  if(mainTab==="output")return(<div className="card-scroll"><div className="mx-wrap"><table className="mx"><thead><tr><th className="corner">{t("matrix.signal")}</th>{boCols.map(c=><th key={c} className="col-bo">{c}</th>)}{ledCols.map(c=><th key={c} className="col-led">{c}</th>)}</tr></thead><tbody>
    <tr className="mx-section"><td colSpan={allCols.length+1}>{t("matrix.binaryInputs")}</td></tr>
    {biRows.map(r=><tr key={r}><td className="row-label is-bi">{r}</td>{allCols.map(c=><td key={c}><div className="mx-cell"><div className={`mx-chk ${outMatrix[r]?.[c]?"on":""}`} onClick={()=>toggleMatrix(r,c)}/></div></td>)}</tr>)}
    <tr className="mx-section"><td colSpan={allCols.length+1}>{t("matrix.cbStatus")}</td></tr>
    {cbStatusRows.map(r=><tr key={r}><td className="row-label" style={{color:'var(--sky)'}}>{r}</td>{allCols.map(c=><td key={c}><div className="mx-cell"><div className={`mx-chk ${outMatrix[r]?.[c]?"on":""}`} onClick={()=>toggleMatrix(r,c)}/></div></td>)}</tr>)}
    <tr className="mx-section"><td colSpan={allCols.length+1}>{t("matrix.cbCommands")}</td></tr>
    {cbCmdRows.map(r=><tr key={r}><td className="row-label" style={{color:'var(--amber)'}}>{r}</td>{allCols.map(c=><td key={c}><div className="mx-cell"><div className={`mx-chk ${outMatrix[r]?.[c]?"on":""}`} onClick={()=>toggleMatrix(r,c)}/></div></td>)}</tr>)}
    <tr className="mx-section"><td colSpan={allCols.length+1}>{t("matrix.protectionStages")}</td></tr>
    {protStageRows.map(r=><tr key={r}><td className="row-label is-prot">{r}</td>{allCols.map(c=><td key={c}><div className="mx-cell"><div className={`mx-chk ${outMatrix[r]?.[c]?"on":""}`} onClick={()=>toggleMatrix(r,c)}/></div></td>)}</tr>)}
  </tbody></table></div></div>);

  if(mainTab==="scenarios")return(<ScenariosSidebar pfMode={phasors.pfMode} setPfMode={phasors.setPfMode} prot={prot} outMatrix={outMatrix} inMatrix={inMatrix} phasors={phasors} applyTestPreset={applyTestPreset} sys={sys}/>);

  return(<div className="card-scroll"><div className="mx-wrap">
    <table className="mx"><thead><tr>
      <th className="corner">{t("matrix.signal")}</th>
      {biRows.map(c=><th key={c} className="col-bo">{c}</th>)}
    </tr></thead><tbody>
      <tr className="mx-section"><td colSpan={biRows.length+1}>{t("matrix.cbStatus")}</td></tr>
      {inMatrixRows.map(r=><tr key={r}><td className="row-label" style={{color:'var(--sky)'}}>{r}</td>{biRows.map(c=><td key={c}><div className="mx-cell"><div className={`mx-chk ${inMatrix[r]?.[c]?"on":""}`} onClick={()=>toggleInMatrix(r,c)}/></div></td>)}</tr>)}
    </tbody></table>
    <div style={{marginTop:16,padding:'10px 12px',background:'var(--card2)',borderRadius:'var(--rs)',border:'1px solid var(--bdr)',fontSize:10,fontFamily:'var(--fm)',color:'var(--tx3)',lineHeight:1.7}}>
      <span style={{color:'var(--sky)',fontWeight:700}}>CB_Opened</span> → {t("customScenarios.infoCbOpened")}<br/>
      <span style={{color:'var(--sky)',fontWeight:700}}>CB_Closed</span> → {t("customScenarios.infoCbClosed")}
    </div>
  </div></div>);
}
